source 'https://github.com/CocoaPods/Specs.git'

target 'SWToolbox', :exclusive => true do
  pod "SWToolbox", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SWToolbox", :path => "../"

  
end
